export enum WeatherTypes {
    Sunny = 1,
    Mostly_Sunny = 2,
    Partly_Sunny = 3,
    Intermittent_Clouds = 4,
    Hazy_Sunshine = 5,
    Mostly_Cloudy = 6,
    Cloudy = 7,
    Dreary_Overcast = 8,
    Fog = 11,
    Showers = 12,
    Mostly_Cloudy_w_Showers = 13,
    Partly_Sunny_w_Showers = 14,
    T_Storms = 15,
    Mostly_Cloudy_w_T_Storms = 16,
    Partly_Sunny_w_T_Storms = 17,
    Rain = 18,
    Flurries = 19,
    Mostly_Cloudy_w_Flurries = 20,
    Partly_Sunny_w_Flurries = 21,
    Snow = 22,
    Mostly_Cloudy_w_Snow = 23,
    Ice = 24,
    Sleet = 25,
    Freezing_Rain = 26,
    Rain_and_Snow = 29,
    Hot = 30,
    Cold = 31,
    Windy = 32,
    Clear = 33,
    Mostly_Clear = 34,
    Partly_Cloudy = 35,
    Intermittent_Clouds_2 = 36,
    Hazy_Moonlight = 37,
    Mostly_Cloudy_2 = 38,
    Partly_Cloudy_w_Showers = 39,
    Mostly_Cloudy_w_Showers_2 = 40,
    Partly_Cloudy_w_T_Storms = 41,
    Mostly_Cloudy_w_T_Storms_2 = 42,
    Mostly_Cloudy_w_Flurries_2 = 43,
    Mostly_Cloudy_w_Snow_2 = 44,


}